spring:
  cloud:
   gateway:
     routes:
       - id: Product-Service
         uri: http://localhost:8081
         predicates:
           - Path=/product/**
       - id:  Cart-Service
         uri: http://localhost:8000
         predicates:
           - Path=/cart/**
       - id: Profile-Service
         uri: http://localhost:8082
         predicates:
           - Path=/profile/**  
       - id: Order-Service
         uri: http://localhost:8083
         predicates:
           - Path=/orders/**   